resources:
  - name: npmHelloWorld_repo
    type: GitRepo
    configuration:
      path: dishameswania/Trial2
      gitProvider: github-disha
  - name: helloworld_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: artdisha
      buildName: npm_example
      buildNumber: 1
      
pipelines:
  - name: npm_example
    steps:
      - name: build_npm
        type: NpmBuild
        configuration:
          repositoryName: npm-remote
          sourceLocation: .
          inputResources:
            - name: npmHelloWorld_repo
          integrations:
            - name: artdisha
      - name: publish_npm
        type: NpmPublish
        configuration:
          repositoryName: npm-local
          inputSteps:
            - name: build_npm
          integrations:
            - name: artdisha
      - name: publish_build_info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: publish_npm
          outputResources:
            - name: helloworld_build_info
